### ISSUE TITLE
Address/test multiple gaps in baseline stock/energy and technology characteristics data

### ISSUE THREAD

**Issue by jtlangevin** [trynthink/scout#140]
1. No stock or energy data for the 'TV' technology are shown.
2. Certain commercial cooking technologies appear incomplete/inconsistent relative to those names used in the baseline technology characteristics data, namely: 

- 'Range, Electric, 4 burner, oven, 11-inch gr' (should be 'Range, Electric, 4 burner, oven, 11-inch griddle')
- 'Range, Electric-induction, 4 burner, oven, 1' (should be 'Range, Electric-induction, 4 burner, oven, 11-inch')
- 'Range, Gas, 4 powered burners, convect. oven' (should be 'Range, Gas, 4 powered burners, convect. oven, 11-i')

**Comment by jtlangevin** [comment]
The gap in TV technology stock/energy data was fixed by commit c057e2ca584934bcab48760c931793450a51b65e.

**Comment by trynthink** [comment]
The problem with the commercial cooking technology names not matching arises from the difference in the allowable length of the technology name or description in the source AEO data files. In "KSDOUT.txt," which is the source of the names for the stock and energy data, the descriptions are limited to 44 characters. In "ktek.csv," which is the source of the technology characteristics data, the descriptions are limited to 50 characters. As a result, the descriptions output to the corresponding JSON data files are different lengths.

The length mismatch is compounded in the 2015 AEO data because the special characters are mistranslated, as in _Range, Electric, 4 burner, oven, 11&quot; gr_ instead of _Range, Electric, 4 burner, oven, 11" gr_. This problem is corrected by "com_mseg.py" by replacing _&quot;_ with _-inch_, but this makes the string length 43 characters instead of 44. As a result, any correction to this problem will likely require truncating all technology names to 43 characters.
