### ISSUE TITLE
Address gaps in baseline technology characteristics data

### ISSUE THREAD

**Issue by jtlangevin** [trynthink/scout#169]
The following end uses currently have incomplete technology data.

Residential:

- "other (grid electric)" (only the "other MELs" technology within this end use category can't be handled),
- "TVs",
- "computers",
- "secondary heating",
- "fans & pumps", and
- "ceiling fan".

Commercial: 

- "PCs",
- "non-PC office equipment", and
- "MELs".

Technologies with incomplete data are formatted differently between the residential and commercial building sectors. Residential technologies have filled out keys and 'NA' values for 'installed cost', 'performance', etc., while commercial technologies are either assigned a single zero value or, in the case of envelope technologies, are filled out with zero values for 'installed cost,' 'performance,' etc. Suggest moving to the latter approach across all residential technologies going forward.

**Comment by robertfares** [comment]
Can you clarify exactly which data fields are missing for each technology? I've been slogging through the JSONs which is very slow since the files are so large.

**Comment by trynthink** [comment]
In general, for all of the end uses in the issue description, there are no cost, performance, lifetime, or consumer choice data provided. That said, some of those end uses have child technologies that weren't listed. The cost, performance, lifetime, and consumer choice parameters should appear in the JSON after the keys in the structures below. While not enclosed in quotes, these strings appear exactly as they are in the JSON.

### Residential (all building types)
#### electricity
- ceiling fan
- fans & pumps
- computers
  - monitors
  - network equipment
  - desktop PC
  - laptop PC
- TVs
  - video game consoles
  - home theater & audio
  - DVD
  - TV
  - set top box
- other (grid electric)
  - other MELs
- secondary heating
  - supply
    - non-specific
#### natural gas
- secondary heating
  - supply
    - non-specific
#### distillate
- secondary heating
  - supply
    - non-specific
#### other fuel
- secondary heating
  - supply
    - secondary heating (kerosene)
    - secondary heating (LPG)
    - secondary heating (coal)
    - secondary heating (wood)

As indicated in the issue description, in the residential data, below each of the indicated keys there will be the following dict structure that is "empty" (populated with "NA" values).

- lifetime
  - average
  - range
  - source
  - units
- consumer choice
  - competed market share
    - parameters
      - b1
      - b2
    - source
- performance
  - typical
  - best
  - source
  - units
- installed cost
  - typical
  - best
  - source
  - units

### Commercial (all building types)
#### electricity
- PCs
- non-PC office equipment
- MELs
  - medical imaging
  - video displays
  - kitchen ventilation
  - lab fridges and freezers
  - laundry
  - security systems
  - escalators
  - fume hoods
  - large video displays
  - coffee brewers
  - elevators
  - non-road electric vehicles
  - distribution transformers

As noted in the issue description, for commercial buildings, these keys are followed by a 0, rather than a data structure populated with "NA" values denoting the missing data.

**Comment by jtlangevin** [comment]
@trynthink thanks for the details. One additional note: the "NA" and zero values currently in the data will be replaced with time-resolved values for cost, performance, and lifetime, which are stored in a dict. Typical performance data, for example, would be accessed by [technology name] -> "performance" -> "typical" -> {"2012": val2012, "2013": val2013, ... "2050": val2050}.

It will likely be difficult to project these values that far into the future; for now, adding cost/performance/lifetime data for electronics/MELs technologies as found on the market today would be a good starting point.

**Comment by robertfares** [comment]
Thanks for the clarifications. I was thinking the stock/consumption data were missing, since these entries were previously missing for TVs, and was confused to find they weren't missing. I'll see what I can dig up.

**Comment by robertfares** [comment]
So I've been going down the MELs rabbit hole lately and found a lot of good data. Mostly stuff from the DOE standards, which exist for a surprising number of MELs. See the attached spreadsheet, which lists which data are available for each residential Other/MEL end use identified in the QTR (beyond just those in Scout), and links to the data source. 

I am going to write something up at Marina's request summarizing the status of the data and identifying options for how to proceed. That will go into a little more detail. I'll share that when it's done.

I'm going to begin chipping away at the commercial "Other/MELs" end uses soon.

[Status of Residential MELs Data.xlsx](https://github.com/trynthink/scout/files/1072392/Status.of.Residential.MELs.Data.xlsx)

**Comment by jtlangevin** [comment]
@robertfares @trynthink note that after commit 907d5af80289cb10d1234e78d724a1c096358109, 'add-on' ECMs with units of relative savings for energy performance will no longer require the availability of complete cost, performance, and lifetime data for comparable baseline technologies.

**Comment by trynthink** [comment]
These data have been added to the input data files for Scout (completed with commit 0d6918a7a49fce1072e95dda9c1736d1d37da322) with the exception of two cases. 

1. Residential "secondary heating" and "other (grid electric)" end uses were not included because they are too ambiguous to specify technology costs or performance.
2. Commercial cost data available in cpl_envelope_mels.json for the "non-PC office equipment" and "MELs" end uses were not brought into cpl_res_com_*.json because of cost unit differences (discussed in issue #227).
