### ISSUE TITLE
Commercial major equipment cost data are wrong due to a conversion error

### ISSUE THREAD

**Issue by jtlangevin** [trynthink/scout#217]
Commercial baseline technology cost data for major equipment types are [converted in 'com_mseg_tech.py'](https://github.com/trynthink/scout/blob/f672af109aca4cf48a20d64ac9167059c52beac8/com_mseg_tech.py#L584-L654) from raw EIA cost units of $/service demand to $/ft<sup>2</sup>. EIA service demand data for each end use are normalized by the square footage served to develop the appropriate conversion factors. However, this reflects a misinterpretation of the raw EIA cost units, which are in $/service _capacity_ (e.g., $/kBtu/h cooling), not $/service _demand_. 

There also appear to be issues with how the units of service demand are interpreted from the raw EIA data (for example, data that are actually in TBtus in the EIA data are expected in MMBtus in the cost conversion routine).

These issues have been addressed by modifying 'com_mseg_tech.py' such that the commercial baseline technology costs are converted from $/service capacity to $/ft<sup>2</sup> using the conversion factors in [this file](https://github.com/trynthink/scout/blob/master/supporting_data/convert_data/ecm_cost_convert.json), which are also used to convert ECM $/service capacity to $/ft<sup>2</sup> for commercial buildings.

**Comment by trynthink** [comment]
Comparing the commercial technology cost data file (ktekx.xlsx) to the [EIA - Technology Forecast Updates – Residential and Commercial Building Technologies – Reference Case](https://www.eia.gov/analysis/studies/buildings/equipcosts/pdf/appendix-a.pdf) data, it becomes apparent that the commercial technology cost data have units of $/kBtu/h capacity. For example, in the published reference case cost data, the total installed capital cost for rooftop air-source heat pumps is 7550 2017$ and the typical capacity is 90 kBtu/h or 83.89 2017$/kBtu/h, which matches the data in the commercial technology cost file. Moreover, the documentation in the cost data file states that the costs are per unit of service demand, but the units given are "2015$/1000 Btu out/hour," which indicates that the costs are capacity-based.

In addition to the misuse of service demand data to adjust the commercial technology costs, because the goal was to obtain prices in $/ft<sup>2</sup>, total square footage was used to calculate service demand per square foot. Because the total square footage data are not provided at the technology level, dividing by total square footage meant we were applying too much floor area to any given technology. As a result, the conversion multiplier reduced the converted cost for commercial building technologies well below expected levels.

**Comment by trynthink** [comment]
Will the changes that resolve this issue also be sufficient to close issue #124?

**Comment by jtlangevin** [comment]
I believe that issue just required tests be added of the conversion, which I believe we have now. So I'd say yes.
