### ISSUE TITLE
Energy Saving Estimation for Certain States?

### ISSUE THREAD

**Issue by suidi1990** [trynthink/scout#221]
Hi!

Is there anyway to calculate the savings for one state in Scout instead of for the whole climate zone?

Thanks!

**Comment by jtlangevin** [comment]
@suidi1990 this is an area of increasing interest. For now, the best way to do it is to develop an appropriate [market scaling fraction](https://scout-bto.readthedocs.io/en/latest/tutorials.html#market-scaling-fractions) to represent the portion of energy use in each AIA climate zone (which Scout uses) that is attributable to the state of interest.

If you don't have your own source already for developing this fraction, you can feel free to reference the population-weighted scaling fractions we've developed [here](https://docs.google.com/spreadsheets/d/1zT7DFaBNU8Oq2ofPv4SBKvbhk15n-Daz-ayhpczr8Q4/edit?usp=sharing) (see the tab "State->AIA_CZ"). For example, the highlighted NY row shows that NY represents ~9% of AIA CZ1, ~8% of AIA CZ2, and ~15% of AIA CZ3. These would be the market scaling fractions you'd use in the measure definition (and see tutorial link above):

"market_scaling_fractions": {"AIA_CZ1": 0.09, "AIA_CZ2": 0.08, "AIA_CZ3": 0.17}

Going forward, we plan to develop an alternate version of our baseline database that splits the baseline data by state, rather than climate zone, so that you don't need to use these market scaling fractions for state-level analyses.

**Comment by trynthink** [comment]
State-level inputs and results outputs were implemented in release [0.7.1](https://github.com/trynthink/scout/releases/tag/v0.7.1).
