### ISSUE TITLE
Defaults for ecm_prep.py error based on regions

### ISSUE THREAD

**Issue by dewittpe** [trynthink/scout#275]
As with #273 a clean v0.8 environment will error.

![image](https://user-images.githubusercontent.com/3136617/189192326-49eb2334-81d0-4ac5-95c9-56774f8a55c5.png)

Again, I would expected that the default settings for ecm_prep.py should be sufficient.

**Comment by jtlangevin** [comment]
@dewittpe this is expected behavior, though as you note not necessarily intuitive. Ultimately we need to overhaul the `climate_zone` input to be more general (e.g., rename to `region`) since it's no longer just AIA climate zones; we also should probably switch the default region settings to EMM, which would avoid this error. However, those changes will take longer to implement and verify. 

For now, we have this error message to inform users of what to do, and I will also add some guidance to the Quick Start Guide about running the standard set of ECMs with default settings. Let's leave this open until we have a more permanent solution.

**Comment by aspeake** [comment]
@aspeake plans on updating the `--alt_regions` default to `EMM` in a future PR
