### ISSUE TITLE
v0.8: 'ENERGY STAR Res. ASHP (FS) + Env.' missing attribute data

### ISSUE THREAD

**Issue by dewittpe** [trynthink/scout#276]
After removing a lot of ECM files to avoid #273 and #275 I have run into an other ECM definition file breaking the ecm_prep.py with defaults:

```
Updating ECM 'ENERGY STAR Res. ASHP (FS) + Env.'...Traceback (most recent call last):
  File "/Users/peterdewitt/NREL/scout/ecm_prep.py", line 13724, in <module>
    main(base_dir)
  File "/Users/peterdewitt/NREL/scout/ecm_prep.py", line 13471, in main
    meas_prepped_objs = prepare_packages(
  File "/Users/peterdewitt/NREL/scout/ecm_prep.py", line 12262, in prepare_packages
    raise ValueError(
ValueError: Contributing ECM 'ENERGY STAR Res. ASHP (FS)' cannot be added to package 'ENERGY STAR Res. ASHP (FS) + Env.' due to missing attribute data for this ECM
```

**Comment by dewittpe** [comment]
Apparently, a ad hoc solution is to replace the versioned `ecm_definitions/package_ecm.json` file with an file with the only contents being: `[]`

**Comment by jtlangevin** [comment]
@dewittpe this error was due to the fact that you had removed one or more of the contributing ECMs that are required to run this package. Because those ECM data weren't prepared, the package they contributed to failed as well. Keeping those ECMs in (while addressing the other issues you raised) will work, so I'm going to close this issue.
